language: python
python:
  - 3.4
  - 3.5

install:
- pip install --upgrade setuptools
- pip install hiredis
- pip install pyflakes
- pip install pep8
- pip install coveralls
- pip install aiohttp
- pip install aioredis
- pip install cryptography
- pip install pynacl
- python setup.py develop

script:
- pyflakes aiohttp_session tests
- pep8 aiohttp_session tests
- coverage run --source=aiohttp_session setup.py test

after_success:
- coveralls

env:
  global:
  - REDIS_PORT=6379
  matrix:
  - PYTHONASYNCIODEBUG=x
  - PYTHONASYNCIODEBUG=
services:
  - redis-server
sudo: false
